### ISSUE TITLE
How do you generate the tiny, small, medium, etc. datasets?

### ISSUE THREAD

**Issue by BarclayII** [IllinoisGraphBenchmark/IGB-Datasets#38]
I was wondering how you the datasets with different sizes are generated.  What is the algorithm to downsample from the complete dataset?

**Comment by akhatua2** [comment]
We randomly sample the whole dataset. No particular algorithm.

**Comment by yichuan520030910320** [comment]
BTW, Why is the training node accuracy for IGB much lower than the validation and test accuracy? Usually, based on OGB experience, due to the existence of dropout, there might be around a 1% drop, but here there's a difference of 10%, which is quite peculiar. Is there any specific algorithm or method used by IGB when splitting the train, validation, and test datasets that could lead to this situation?
![174f1fe042b3c3547b1fcf67adbd78d](https://github.com/IllinoisGraphBenchmark/IGB-Datasets/assets/73766326/a4ccacb3-f157-4a99-bc90-9805e7b72267)

**Comment by BarclayII** [comment]
But how do you randomly sample?  Like, uniformly randomly taking the nodes and then inducing a subgraph?

**Comment by akhatua2** [comment]
Yep
